Config = {}

Config.Locations = {
    ["main"] = {
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },
    ["thermite"] = {
        x = -708.88, 
        y = -294.84, 
        z = 36.99,
        isDone = false,
        isBusy = false,
    },
    ["takeables"] = {
        [1] = {
            x = -638.65, 
            y = -282.06, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 4},
        },
        [2] = {
            x = -637.07, 
            y = -281.14, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 6},
        },
        [3] = {
            x = -635.45, 
            y = -280.22, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [4] = {
            x = -633.73, 
            y = -279.21, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "samsungphone", amount = 6},
        },
        [5] = {
            x = -632.07, 
            y = -278.26, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 4},
        },
        [6] = {
            x = -630.71, 
            y = -280.51, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [7] = {
            x = -632.37, 
            y = -281.47, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 4},
        },
        [8] = {
            x = -634.08, 
            y = -282.46, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "iphone", amount = 6},
        },
        [9] = {
            x = -635.64, 
            y = -283.41, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 4},
        },
        [10] = {
            x = -637.29, 
            y = -284.31, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 3},
        },
        [11] = {
            x = -635.55, 
            y = -277.21, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "laptop", amount = 1},
        },
        [12] = {
            x = -631.82, 
            y = -283.97, 
            z = 35.57,
            isDone = false,
            isBusy = false,
            reward =  {name = "tablet", amount = 2},
        },
    },
    ["safe"] = {
        x = -625.37, 
        y = -283.74, 
        z = 35.57,
        isDone = false,
        isBusy = false,
    }
}

Config.MaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [18] = true,
    [26] = true,
    [52] = true,
    [53] = true,
    [54] = true,
    [55] = true,
    [56] = true,
    [57] = true,
    [58] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [112] = true,
    [113] = true,
    [114] = true,
    [118] = true,
    [125] = true,
    [132] = true,
}

Config.FemaleNoHandshoes = {
    [0] = true,
    [1] = true,
    [2] = true,
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [15] = true,
    [19] = true,
    [59] = true,
    [60] = true,
    [61] = true,
    [62] = true,
    [63] = true,
    [64] = true,
    [65] = true,
    [66] = true,
    [67] = true,
    [68] = true,
    [69] = true,
    [70] = true,
    [71] = true,
    [129] = true,
    [130] = true,
    [131] = true,
    [135] = true,
    [142] = true,
    [149] = true,
    [153] = true,
    [157] = true,
    [161] = true,
    [165] = true,
}