Config = {}

Config.Locations = {
    ["vehiclegundealer"] = {
        label = "Car Spawn",
        coords = {x = 106.15, y = -1942.45, z = 20.8},
    },
    ["gundealerweapons"] = {
        label = "Gun Dealer Armory",
        coords = {x = 117.6, y = -1950.23, z = 20.75},
    },
    ["stashgundealer"] = {
        label = "Gun Dealer Stash",
        coords = {x = 114.3, y = -1961.27, z = 21.33},
    },
}

Config.Vehicles = {
    ["elegy"] = "Elegy",

}

Config.GunDealer = {
    label = "Gun Dealer Armory",
    slots = 30,
    items = {
        [1] = {
            name = "weapon_knife",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_switchblade",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_pistol",
            price = 2500,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "weapon_pistol50",
            price = 6000,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "weapon_combatpistol",
            price = 4000,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "weapon_microsmg",
            price = 12000,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "weapon_machinepistol",
            price = 9500,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "weapon_carbinerifle",
            price = 35000,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "weapon_assaultrifle",
            price = 20000,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "weapon_stungun",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "weapon_compactrifle",
            price = 16000,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "weapon_heavypistol",
            price = 6000,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "weapon_smg",
            price = 14000,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "pistol_ammo",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "rifle_ammo",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "smg_ammo",
            price = 50,
            amount = 1000,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "pistol_suppressor",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "pistol_extendedclip",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "smg_extendedclip",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "smg_flashlight",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "smg_scope",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "smg_suppressor",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "rifle_extendedclip",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "rifle_drummag",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "rifle_suppressor",
            price = 3000,
            amount = 1000,
            info = {},
            type = "item",
            slot = 25,
        },
    }
}