Config = {}

Config.Webhooks = {
    ["default"] = "DISCORD WEBHOOK URL",
    ["playermoney"] = "DISCORD WEBHOOK URL",
    ["playerinventory"] = "DISCORD WEBHOOK URL",
    ["robbing"] = "DISCORD WEBHOOK URL",
    ["cuffing"] = "DISCORD WEBHOOK URL",
    ["drop"] = "DISCORD WEBHOOK URL",
    ["trunk"] = "DISCORD WEBHOOK URL",
    ["stash"] = "DISCORD WEBHOOK URL",
    ["glovebox"] = "DISCORD WEBHOOK URL",
    ["banking"] = "DISCORD WEBHOOK URL",
    ["vehicleshop"] = "DISCORD WEBHOOK URL",
    ["vehicleupgrades"] = "DISCORD WEBHOOK URL",
    ["shops"] = "DISCORD WEBHOOK URL",
    ["dealers"] = "DISCORD WEBHOOK URL",
    ["storerobbery"] = "DISCORD WEBHOOK URL",
    ["bankrobbery"] = "DISCORD WEBHOOK URL",
    ["powerplants"] = "DISCORD WEBHOOK URL",
    ["death"] = "DISCORD WEBHOOK URL",
    ["joinleave"] = "DISCORD WEBHOOK URL",
    ["ooc"] = "DISCORD WEBHOOK URL",
    ["report"] = "DISCORD WEBHOOK URL",
    ["me"] = "DISCORD WEBHOOK URL",
    ["pmelding"] = "DISCORD WEBHOOK URL",
    ["112"] = "DISCORD WEBHOOK URL",
    ["bans"] = "DISCORD WEBHOOK URL",
    ["anticheat"] = "DISCORD WEBHOOK URL",
    ["weather"] = "DISCORD WEBHOOK URL",
    ["moneysafes"] = "DISCORD WEBHOOK URL",
    ["bennys"] = "DISCORD WEBHOOK URL",
}

Config.Colors = {
    ["default"] = 16711680,
    ["blue"] = 25087,
    ["green"] = 762640,
    ["white"] = 16777215,
    ["black"] = 0,
    ["orange"] = 16743168,
    ["lightgreen"] = 65309,
    ["yellow"] = 15335168,
    ["turqois"] = 62207,
    ["pink"] = 16711900,
    ["red"] = 16711680,
}